export const DESCFOROWNERS_LOADING = 'DESCFOROWNERS_LOAD';
export const DESCFOROWNERS_ERROR = 'DESCFOROWNERS_ERROR';
export const DESCFOROWNERS_ADD_ALL = 'DESCFOROWNERS_ADD_ALL';
export const DESCFORBUYERS_LOADING = 'DESCFORBUYERS_LOADING';
export const DESCFORBUYERS_ERROR = 'DESCFORBUYERS_ERROR';
export const DESCFORBUYERS_ADD_ALL = 'DESCFORBUYERS_ADD_ALL';